### ISSUE TITLE
import gdal and ogr in vector.py

### ISSUE THREAD

**Issue by couasnonanais** [ElcoK/DamageScanner#16]
I am not sure why but import gdal and import ogr do not run anymore. I had to change these lines to from osgeo import gdal/ogr to have it work again. I guess soemthing went wrong with the installation? This was an issue for others as well so I thought I would put it here as an issue to solve..

**Comment by ElcoK** [comment]
Oh I fixed this on Philip's request. Long-standing issue but is solved.
